#ifndef	DAR_VR_FIX_VERSION_INCLUDED
#define DAR_VR_FIX_VERSION_INCLUDED

#define MAKE_STR_HELPER(a_str) #a_str
#define MAKE_STR(a_str) MAKE_STR_HELPER(a_str)

#define DAR_VR_FIX_VERSION_MAJOR 1
#define DAR_VR_FIX_VERSION_MINOR 0
#define DAR_VR_FIX_VERSION_PATCH 0
#define DAR_VR_FIX_VERSION_BETA	0
#define DAR_VR_FIX_VERSION_VERSTRING MAKE_STR(DAR_VR_FIX_VERSION_MAJOR) "." MAKE_STR(DAR_VR_FIX_VERSION_MINOR) "." MAKE_STR(DAR_VR_FIX_VERSION_PATCH) "." MAKE_STR(DAR_VR_FIX_VERSION_BETA)

#endif
